name: Build and upload to PyPI

on:
  merge_group:
    branches:
      - 'main'
  release:
    types:
        - published

jobs:
  update_version:
    name: update version
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: Update version on merge
        if: github.event_name == 'merge_group'
        run:  |
            python tools/version.py "beta"
      - name: Update version on release
        if: github.event_name == 'release'
        run: |
            python tools/version.py "minor"
      - name: Store changes
        uses: actions/upload-artifact@v3
        with:
          name: setup
          path: setup.py


  build_wheels:
    name: Build and test wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: [update_version]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - uses: actions/download-artifact@v3
        with:
          name: setup
      - name: build wheel
        uses: pypa/cibuildwheel@v2.8.0
        env:
          # List of platforms to build on (incl. Python version)
          CIBW_BUILD: cp3{8,9,10}-manylinux_x86_64 cp3{8,9,10}-win_amd64 cp3{8,9,10}-macosx_x86_64 cp38-macosx_arm64

          CIBW_BEFORE_BUILD: >
             pip install numpy cython==0.29.32 scipy joblib
          # Install test dependencies and run tests
          CIBW_TEST_REQUIRES: pytest joblib
          CIBW_TEST_COMMAND: >
            pytest {project}/test
      - name: upload wheel
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  upload_pypi:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: mint API token
        id: mint
        uses: tschm/token-mint-action@v1.0.2

      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - name: Publish package distribution to PYPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ steps.mint.outputs.api-token }}


  update_setup:
    needs: [upload_pypi]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - uses: actions/download-artifact@v3
        with:
          name: setup
      - name: Commit on merge
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update version number
          commit_user_email: actions@github
